apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
data:
  # Enable end-to-end encryption
  tls.config: |
    ciphers: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
    minVersion: "1.2"
    maxVersion: "1.3"

  # ArgoCD server configuration for end-to-end TLS
  server.config: |
    url: https://argocd.dev.magebase.dev
    grpc.web: true
    insecure: false

    # Certificate configuration
    tls:
      config:
        certs:
          server.crt: |
          server.key: |
