apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-http
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argocd-dev.magebase.dev`) && PathPrefix(`/.well-known/acme-challenge`)
      priority: 15
      services:
        - name: cm-acme-http-solver-4zxbf
          port: 8089
    - kind: Rule
      match: Host(`argocd-dev.magebase.dev`)
      middlewares:
        - name: redirect-https
          namespace: argocd
      priority: 10
      services:
        - name: argocd-server
          port: 80
