apiVersion: apps/v1
kind: Deployment
metadata:
  name: magebase-app
  namespace: magebase
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: magebase
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: magebase-db
  namespace: magebase
spec:
  instances: 3
  storage:
    size: 50Gi
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "1GB"
      effective_cache_size: "4GB"
      maintenance_work_mem: "256MB"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magebase-redis
  namespace: magebase
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
