service: magebase
image: magebase/magebase

servers:
  web:
    - deploy@91.99.119.221
  vite:
    hosts:
      - deploy@91.99.119.221
    cmd: bin/vite ssr
    options:
      network-alias: vite_ssr

proxy:
  ssl: true
  host: magebase.dev

registry:
  username: magebase
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - AWS_SES_ACCESS_KEY_ID
    - AWS_SES_SECRET_ACCESS_KEY
  clear:
    AWS_REGION: us-east-1
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: magebase-db
    INERTIA_SSR_URL: http://vite_ssr:13714

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - magebase_storage:/rails/storage

asset_path: /rails/public/assets

builder:
  arch:
    - amd64
    - arm64

accessories:
  db:
    image: postgres:16
    host: 91.99.119.221
    port: "127.0.0.1:5432:5432" # expose to localhost only
    env:
      clear:
        POSTGRES_USER: magebase
        POSTGRES_DB: magebase_production
        INERTIA_SSR_URL: http://vite_ssr:13714
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
