# Development environment patches
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  source:
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 7d  # Shorter retention for dev
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: hcloud-volumes
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi  # Smaller storage for dev
        grafana:
          adminPassword: "admin123"  # Simple password for dev
          persistence:
            enabled: true
            storageClassName: hcloud-volumes
            size: 5Gi  # Smaller storage for dev
