# Production environment patches
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  source:
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 90d  # Longer retention for prod
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: hcloud-volumes
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 100Gi  # Larger storage for prod
            replicas: 2  # HA setup for prod
        grafana:
          adminPassword: ${GRAFANA_ADMIN_PASSWORD}  # Use secret for prod
          persistence:
            enabled: true
            storageClassName: hcloud-volumes
            size: 20Gi  # Larger storage for prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    helm:
      values: |
        server:
          replicas: 2  # HA setup for prod
        redis:
          replicas: 2  # HA setup for prod
