apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: magebase-base

resources:
  - deployment.yaml
  - database.yaml

images:
  - name: magebase-app
    newName: ${IMAGE_REGISTRY}/${IMAGE_NAME}
    newTag: ${IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: magebase-config
    literals:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true

secretGenerator:
  - name: magebase-secrets
    literals:
      - secret-key-base=${SECRET_KEY_BASE}
      - ruby-llm-api-key=${RUBY_LLM_API_KEY}
      - aws-ses-access-key-id=${AWS_SES_ACCESS_KEY_ID}
      - aws-ses-secret-access-key=${AWS_SES_SECRET_ACCESS_KEY}
  - name: aws-s3-credentials
    literals:
      - access_key_id=${AWS_S3_ACCESS_KEY_ID}
      - secret_access_key=${AWS_S3_SECRET_ACCESS_KEY}

patches: []

namespace: magebase
