apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: site-secret-store
  namespace: magebase
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1 # Update to your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: magebase-app-secrets
  namespace: magebase
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: site-secret-store
    kind: SecretStore
  target:
    name: magebase-app-secrets
    creationPolicy: Owner
  data:
    # Application Secrets
    - secretKey: secret-key-base
      remoteRef:
        key: /site/${ENVIRONMENT}/rails/secret-key-base
    - secretKey: ruby-llm-api-key
      remoteRef:
        key: /site/${ENVIRONMENT}/api/ruby-llm-api-key
    - secretKey: aws-ses-access-key-id
      remoteRef:
        key: /site/${ENVIRONMENT}/aws/ses-access-key-id
    - secretKey: aws-ses-secret-access-key
      remoteRef:
        key: /site/${ENVIRONMENT}/aws/ses-secret-access-key
    - secretKey: rails-master-key
      remoteRef:
        key: /site/${ENVIRONMENT}/rails/master-key

    # Database Configuration
    - secretKey: DATABASE_URL
      remoteRef:
        key: /site/${ENVIRONMENT}/database/url

    # AWS S3 Credentials
    - secretKey: aws-s3-access-key-id
      remoteRef:
        key: /site/${ENVIRONMENT}/aws/s3-access-key-id
    - secretKey: aws-s3-secret-access-key
      remoteRef:
        key: /site/${ENVIRONMENT}/aws/s3-secret-access-key

    # Configuration Values
    - secretKey: IMAGE_REGISTRY
      remoteRef:
        key: /site/${ENVIRONMENT}/docker/image-registry
    - secretKey: IMAGE_NAME
      remoteRef:
        key: /site/${ENVIRONMENT}/docker/image-name
    - secretKey: IMAGE_TAG
      remoteRef:
        key: /site/${ENVIRONMENT}/docker/image-tag
    - secretKey: DOMAIN
      remoteRef:
        key: /site/${ENVIRONMENT}/domain
    - secretKey: RAILS_ENV
      remoteRef:
        key: /site/${ENVIRONMENT}/rails/env
    - secretKey: RAILS_LOG_TO_STDOUT
      remoteRef:
        key: /site/${ENVIRONMENT}/rails/log-to-stdout
    - secretKey: RAILS_SERVE_STATIC_FILES
      remoteRef:
        key: /site/${ENVIRONMENT}/rails/serve-static-files
    - secretKey: CLOUDFLARE_R2_ACCESS_KEY_ID
      remoteRef:
        key: /site/${ENVIRONMENT}/cloudflare/r2-access-key-id
    - secretKey: CLOUDFLARE_R2_SECRET_ACCESS_KEY
      remoteRef:
        key: /site/${ENVIRONMENT}/cloudflare/r2-secret-access-key
