apiVersion: apps/v1
kind: Deployment
metadata:
  name: magebase-app
  namespace: magebase
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: magebase
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: magebase-db
  namespace: magebase
spec:
  instances: 1
  storage:
    size: 5Gi
  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
