apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: magebase-dev

bases:
  - ../../base

patchesStrategicMerge:
  - configmap-patch.yaml

images:
  - name: magebase-app
    newTag: dev-${IMAGE_TAG}

namespace: magebase-dev
