apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - uat-patches.yaml

configMapGenerator:
  - name: magebase-config
    behavior: replace
    literals:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true

secretGenerator:
  - name: magebase-secrets
    behavior: replace
    literals:
      - secret-key-base=${SECRET_KEY_BASE}
      - ruby-llm-api-key=${RUBY_LLM_API_KEY}
      - aws-ses-access-key-id=${AWS_SES_ACCESS_KEY_ID}
      - aws-ses-secret-access-key=${AWS_SES_SECRET_ACCESS_KEY}
