apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: magebase-app
  namespace: magebase
spec:
  template:
    spec:
      containers:
        - name: magebase
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: site-uat-cluster-db-url
                  key: DATABASE_URL
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magebase-ingress
  namespace: magebase
spec:
  tls:
    - hosts:
        - uat.magebase.dev
