name: Trigger Workflow in Another Repo
on:
  release:
    types: [published]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/magebase/base-infra/dispatches \
            -d '{"event_type":"trigger-workflow"}'
